{
 "title": "Ceph - Cluster",
 "description": "Ceph cluster overview",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "Exporter Instance",
    "query": "label_values(ceph_health_status, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Health Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_health_status{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "All",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_osd_metadata{instance=~\"$instance\"})",
     "legendFormat": "All",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "In",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osds_in{instance=~\"$instance\"})",
     "legendFormat": "In",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Out",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_in{instance=~\"$instance\"} == bool 0)",
     "legendFormat": "Out",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{instance=~\"$instance\"})",
     "legendFormat": "Up",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Down",
     "crit": 2,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{instance=~\"$instance\"} == bool 0)",
     "legendFormat": "Down",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "Capacity used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes_used{instance=~\"$instance\"})/sum(ceph_osd_stat_bytes{instance=~\"$instance\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "PG States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_pg_total", "legendFormat": "Total" },
    { "expr": "ceph_pg_active", "legendFormat": "Active" },
    { "expr": "ceph_pg_total - ceph_pg_active", "legendFormat": "Inactive" },
    { "expr": "ceph_pg_undersized", "legendFormat": "Undersized" },
    { "expr": "ceph_pg_degraded", "legendFormat": "Degraded" },
    { "expr": "ceph_pg_inconsistent", "legendFormat": "Inconsistent" },
    { "expr": "ceph_pg_down", "legendFormat": "Down" }
   ]
  },
  {
   "title": "OSD Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "quantile(0.95, ceph_osd_apply_latency_ms{instance=~\"$instance\"})",
     "legendFormat": "Apply Latency P_95"
    },
    {
     "expr": "quantile(0.95, ceph_osd_commit_latency_ms{instance=~\"$instance\"})",
     "legendFormat": "Commit Latency P_95"
    },
    {
     "expr": "avg(ceph_osd_apply_latency_ms{instance=~\"$instance\"})",
     "legendFormat": "Avg Apply Latency"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{instance=~\"$instance\"})",
     "legendFormat": "Avg Commit Latency"
    }
   ]
  },
  {
   "title": "Monitors",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "In Quorum",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_mon_quorum_status{instance=~\"$instance\"})",
     "legendFormat": "In Quorum",
     "units": "none",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "Total",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mon_quorum_status{instance=~\"$instance\"})",
     "legendFormat": "Total",
     "units": "none",
     "valueHandler": "Text Only",
     "warn": 2
    },
    {
     "aggregation": "Last",
     "alias": "MONs out of Quorum",
     "crit": 1.6,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "Never",
     "expr": "count(ceph_mon_quorum_status{instance=~\"$instance\"}) / sum(ceph_mon_quorum_status{instance=~\"$instance\"})",
     "legendFormat": "MONs out of Quorum",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1.1
    }
   ]
  },
  {
   "title": "Client connections",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Clients",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "ceph_mds_server_handle_client_session{instance=~\"$instance\"}",
     "legendFormat": "Clients",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Cluster I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Writes"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "In-/Egress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "Bps", "label": " Egress (-) / Ingress (+)" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(ceph_pool_bytes_used{instance=~\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "OSD Capacity Utilization",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{instance=~'$instance'} / ceph_osd_stat_bytes{instance=~'$instance'}",
     "legendFormat": "Util (%)"
    }
   ]
  },
  {
   "title": "PGs per OSD",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "ceph_osd_numpg{instance=~\"$instance\"}",
     "legendFormat": "#PGs"
    }
   ]
  },
  {
   "title": "Recovery Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ops", "label": "Recovery Ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops[1m]))",
     "legendFormat": "Op/s"
    }
   ]
  },
  {
   "title": "OSD Hosts",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (hostname) (ceph_osd_metadata))"
    }
   ]
  },
  {
   "title": "AVG CPU Busy",
   "type": "singlestat",
   "description": "Average CPU busy across all hosts (OSD, RGW, MON etc) within the cluster",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 24 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(\n  1 - (\n    avg by(instance) \n      (irate(node_cpu_seconds_total{mode='idle',instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}[1m]) or\n       irate(node_cpu{mode='idle',instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}[1m]))\n    )\n  )"
    }
   ]
  },
  {
   "title": "AVG RAM Utilization",
   "type": "singlestat",
   "description": "Average Memory Usage across all hosts in the cluster (excludes buffer/cache usage)",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 24 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (((node_memory_MemTotal{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"} or node_memory_MemTotal_bytes{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"})- (\n  (node_memory_MemFree{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"} or node_memory_MemFree_bytes{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"})  + \n  (node_memory_Cached{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"} or node_memory_Cached_bytes{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}) + \n  (node_memory_Buffers{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"} or node_memory_Buffers_bytes{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}) +\n  (node_memory_Slab{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"} or node_memory_Slab_bytes{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"})\n  )) /\n (node_memory_MemTotal{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"} or node_memory_MemTotal_bytes{instance=~\"[[osd_hosts]]|[[rgw_hosts]]|[[mon_hosts]]|[[mds_hosts]].*\"} ))"
    }
   ]
  },
  {
   "title": "Physical IOPS",
   "type": "singlestat",
   "description": "IOPS Load at the device as reported by the OS on all OSD hosts",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum ((irate(node_disk_reads_completed{instance=~\"($osd_hosts).*\"}[5m]) or irate(node_disk_reads_completed_total{instance=~\"($osd_hosts).*\"}[5m]) )  + \n(irate(node_disk_writes_completed{instance=~\"($osd_hosts).*\"}[5m]) or irate(node_disk_writes_completed_total{instance=~\"($osd_hosts).*\"}[5m])))"
    }
   ]
  },
  {
   "title": "Network Load",
   "type": "singlestat",
   "description": "Total send/receive network load across all hosts in the ceph cluster",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 24 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n  irate(node_network_receive_bytes{instance=~\"($osd_hosts|mon_hosts|mds_hosts|rgw_hosts).*\",device!=\"lo\"}[1m]) or\n  irate(node_network_receive_bytes_total{instance=~\"($osd_hosts|mon_hosts|mds_hosts|rgw_hosts).*\",device!=\"lo\"}[1m])\n  ) +\nsum (\n  irate(node_network_transmit_bytes{instance=~\"($osd_hosts|mon_hosts|mds_hosts|rgw_hosts).*\",device!=\"lo\"}[1m]) or\n  irate(node_network_transmit_bytes_total{instance=~\"($osd_hosts|mon_hosts|mds_hosts|rgw_hosts).*\",device!=\"lo\"}[1m])\n  )"
    }
   ]
  },
  {
   "title": "CPU Busy - Top 10 Hosts",
   "type": "graph",
   "description": "Show the top 10 busiest hosts by cpu",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "topk(10,( 1 - (\n    avg by(instance) \n      (irate(node_cpu_seconds_total{mode='idle',instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}[1m]) or\n       irate(node_cpu{mode='idle',instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}[1m]))\n    )\n  )\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Load - Top 10",
   "type": "graph",
   "description": "Top 10 hosts by network load",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, (sum by(instance) (\n  (\n  irate(node_network_receive_bytes{instance=~\"($osd_hosts|mon_hosts|mds_hosts|rgw_hosts).*\",device!=\"lo\"}[1m]) or\n  irate(node_network_receive_bytes_total{instance=~\"($osd_hosts|mon_hosts|mds_hosts|rgw_hosts).*\",device!=\"lo\"}[1m])\n  ) +\n  (\n  irate(node_network_transmit_bytes{instance=~\"($osd_hosts|mon_hosts|mds_hosts|rgw_hosts).*\",device!=\"lo\"}[1m]) or\n  irate(node_network_transmit_bytes_total{instance=~\"($osd_hosts|mon_hosts|mds_hosts|rgw_hosts).*\",device!=\"lo\"}[1m])\n  ))\n  )\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}