{
 "title": "OSD详细指标",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "osd_id",
    "label": "OSD Id",
    "query": "label_values(ceph_osd_metadata,ceph_daemon)"
   }
  ]
 },
 "panels": [
  { "title": "OSD Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OSD $osd_id Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_osd_op_r_latency_sum{ceph_daemon=~\"osd.[[osd_id]]\"}[1m]) / on (ceph_daemon) irate(ceph_osd_op_r_latency_count[1m]) * 1000",
     "legendFormat": "READs"
    },
    {
     "expr": "irate(ceph_osd_op_w_latency_sum{ceph_daemon=~\"osd.[[osd_id]]\"}[1m]) / on (ceph_daemon) irate(ceph_osd_op_w_latency_count[1m]) * 1000",
     "legendFormat": "WRITEs"
    }
   ]
  },
  {
   "title": "OSD $osd_id R/W IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_osd_op_r{ceph_daemon=~\"osd.[[osd_id]]\"}[1m])",
     "legendFormat": "Reads"
    },
    {
     "expr": "irate(ceph_osd_op_w{ceph_daemon=~\"osd.[[osd_id]]\"}[1m])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "OSD $osd_id R/W Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_osd_op_r_out_bytes{ceph_daemon=~\"osd.[[osd_id]]\"}[1m])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "irate(ceph_osd_op_w_in_bytes{ceph_daemon=~\"osd.[[osd_id]]\"}[1m])",
     "legendFormat": "Write Bytes"
    }
   ]
  }
 ]
}