global:
  scrape_interval:     15s 
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
      - targets: ['10.127.7.80:9093']

rule_files:
  - "ceph_default_alerts.yml"
  - "hoststat-alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.127.7.80:9090']
  - job_name: 'ceph'
    static_configs:
        - targets: ['10.127.7.80:9283','10.127.7.81:9283','10.127.7.82:9283']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['10.127.7.81:9100','10.127.7.80:9100','10.127.7.82:9100']
