alerting:
  alertmanagers:
  - static_configs:
    - targets: ['192.168.0.11:9093']
global: {evaluation_interval: 15s, scrape_interval: 15s}
rule_files: [ceph_default_alerts.yml]
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['192.168.0.11:9090']
- job_name: ceph
  static_configs:
  - targets: ['192.168.0.11:9283', '192.168.0.12:9283', '192.168.0.13:9283']
- job_name: node-exporter
  static_configs:
  - targets: ['192.168.0.11:9100', '192.168.0.12:9100', '192.168.0.13:9100']
